# Generated by Django 5.2.15 on 2026-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200)),
                ('platform_describtion', models.TextField(blank=True)),
                ('company_name', models.CharField(default='BEN', max_length=100)),
            ],
        ),
    ]
