# Generated by Django 5.2.15 on 2026-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='auto_publish_courses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_suffix',
            field=models.CharField(default='VISUAL', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='password_min_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_course_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='session_timeout',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(default='lms.support@benvisual.com', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
